[tool.poetry]
name = "aio-trading-stat"
version = "0.1.0"
description = ""
authors = ["Nikita Korobov <riper5218@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
